apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cert-manager-webhook-hetzner
build:
  artifacts:
    - image: docker.io/hetzner/cert-manager-webhook-hetzner
      ko: {}
  local:
    useBuildkit: true
  insecureRegistries:
    - localhost:30666

deploy:
  helm:
    releases:
      - name: cert-manager-webhook-hetzner
        namespace: cert-manager
        chartPath: chart
