name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  helm:
    runs-on: ubuntu-latest
    name: helm validation ${{ matrix.helm }}
    strategy:
      matrix:
        helm:
          - v3.19.2 # renovate: datasource=github-releases depname=helm/helm versioning=same-major
          - v4.0.0 # renovate: datasource=github-releases depname=helm/helm versioning=same-major

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.x

      - uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c # v0.13.5
        with:
          setup-tools: |
            helm
          helm: ${{ matrix.helm }}

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: none || true # install pre-commit without running any hooks

      # run with pre-commit to get diff check
      - name: helm-validation
        run: |
          pre-commit run update-helm-snapshots --all
          pre-commit run update-helm-docs --all

  pre-commit:
    runs-on: ubuntu-latest
    env:
      # Helm lints are executed in a separate action with a version matrix
      SKIP: "update-helm-snapshots,update-helm-docs"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.x

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
